PYTHON   := python3
THREADS  := 8

# ──────────────────────────────────────────────────────────────────────────────
# soloLTRs: Cossu M/U pipeline
#
# Goal: reproduce and then accelerate Cossu et al. 2017 (GBE, DOI: 10.1093/gbe/evx260)
#   Phase 1 — Reproduce: BLAST-based tag search + BWA ALN tract mapping
#   Phase 2 — Accelerate: replace BLAST with minimap2 (7.6x speedup)
#   Phase 3 — Multi-species: validate all 11 Cossu species
# ──────────────────────────────────────────────────────────────────────────────

# Paths
COSSU_REF      := references/cossu
COSSU_S1       := $(COSSU_REF)/Supporting_Data_S1
COSSU_ANG      := $(COSSU_S1)/ANGIOSPERMS
COSSU_CON      := $(COSSU_S1)/CONIFERS
COSSU_EXPECTED := $(COSSU_REF)/expected_ratios.tsv

# ── Legacy Arabidopsis paths (Phase 1/2) ─────────────────────────────────────
AT_PARALOGS    := $(COSSU_ANG)/complete_Arabidopsis.fa
AT_READS_R1    := data/reads/arabidopsis/ERR171441_1.fastq.gz
AT_READS_R2    := data/reads/arabidopsis/ERR171441_2.fastq.gz
AT_OUT_MM2     := data/cossu/arabidopsis-mm2
AT_OUT_BLAST   := data/cossu/arabidopsis-blast
# Legacy path (Phase 1 validated results) — untouched by Phase 2 targets
AT_OUT         := data/cossu/arabidopsis

# ── Phase 3: Multi-species species table ─────────────────────────────────────
# Format: SPECIES_$(key)_SRA, SPECIES_$(key)_PARALOGS
# Reads expected at: data/reads/$(key)/$(SRA)_1.fastq.gz data/reads/$(key)/$(SRA)_2.fastq.gz
# Output goes to:    data/cossu/$(key)-mm2/results.tsv

SPECIES_LIST := arabidopsis amborella brachypodium oryza populus vitis zea \
                picea_abies picea_glauca pinus_taeda pinus_lambertiana

# Angiosperms
SPECIES_arabidopsis_SRA      := ERR171441
SPECIES_arabidopsis_PARALOGS := $(COSSU_ANG)/complete_Arabidopsis.fa

SPECIES_amborella_SRA        := SRR954506
SPECIES_amborella_PARALOGS   := $(COSSU_ANG)/complete_Amborella.fa

SPECIES_brachypodium_SRA     := SRR494350
SPECIES_brachypodium_PARALOGS := $(COSSU_ANG)/complete_Brachypodium.fa

SPECIES_oryza_SRA            := SRR1450197
SPECIES_oryza_PARALOGS       := $(COSSU_ANG)/complete_Oryza.fa

SPECIES_populus_SRA          := SRR1302874
SPECIES_populus_PARALOGS     := $(COSSU_ANG)/complete_Populus_trichocarpa.fa

SPECIES_vitis_SRA            := SRR931846
SPECIES_vitis_PARALOGS       := $(COSSU_ANG)/complete_Vitis.fa

SPECIES_zea_SRA              := ERR361368
SPECIES_zea_PARALOGS         := $(COSSU_ANG)/complete_Zea_mays.fa

# Conifers (concatenated from per-family FASTAs via prepare-conifers)
SPECIES_picea_abies_SRA          := ERR268359
SPECIES_picea_abies_PARALOGS     := $(COSSU_CON)/complete_Picea_abies.fa

SPECIES_picea_glauca_SRA         := SRR1259601
SPECIES_picea_glauca_PARALOGS    := $(COSSU_CON)/complete_Picea_glauca.fa

SPECIES_pinus_taeda_SRA          := SRR1049544
SPECIES_pinus_taeda_PARALOGS     := $(COSSU_CON)/complete_Pinus_taeda.fa

SPECIES_pinus_lambertiana_SRA    := SRR2027098
SPECIES_pinus_lambertiana_PARALOGS := $(COSSU_CON)/complete_Pinus_lambertiana.fa

# ──────────────────────────────────────────────────
# Cossu M/U pipeline — Arabidopsis (Phase 2)
# ──────────────────────────────────────────────────

## mu-arabidopsis-mm2: now generated by Phase 3 template (see SPECIES_TEMPLATE below)

## mu-arabidopsis-blast: run M/U pipeline with BLAST engine (Phase 1 reference)
mu-arabidopsis-blast: $(AT_READS_R1) $(AT_READS_R2)
	mkdir -p $(AT_OUT_BLAST)
	$(PYTHON) -m scripts.pipeline.cli all \
	  --paralogs $(AT_PARALOGS) \
	  --reads    $(AT_READS_R1) $(AT_READS_R2) \
	  --out-dir  $(AT_OUT_BLAST) \
	  --threads  $(THREADS) \
	  --engine   blast

## mu-benchmark: run both engines and compare per-family S/C ratios (Arabidopsis only)
mu-benchmark: mu-arabidopsis-blast mu-arabidopsis-mm2
	@echo ""
	@echo "=== S/C comparison: BLAST vs minimap2 ==="
	@echo "--- BLAST ---"
	@cat $(AT_OUT_BLAST)/results.tsv
	@echo ""
	@echo "--- minimap2 ---"
	@cat $(AT_OUT_MM2)/results.tsv
	@echo ""
	@echo "--- timings ---"
	@echo "BLAST:"
	@cat $(AT_OUT_BLAST)/timings.tsv
	@echo "minimap2:"
	@cat $(AT_OUT_MM2)/timings.tsv

## mu-prepare-arabidopsis: extract tags only (no reads needed)
mu-prepare-arabidopsis:
	mkdir -p $(AT_OUT_MM2)
	$(PYTHON) -m scripts.pipeline.cli prepare \
	  --paralogs $(AT_PARALOGS) \
	  --out-dir  $(AT_OUT_MM2)

## mu-arabidopsis: legacy alias — run full M/U pipeline (Phase 1 BLAST, original output dir)
mu-arabidopsis: $(AT_READS_R1) $(AT_READS_R2)
	mkdir -p $(AT_OUT)
	$(PYTHON) -m scripts.pipeline.cli all \
	  --paralogs $(AT_PARALOGS) \
	  --reads    $(AT_READS_R1) $(AT_READS_R2) \
	  --out-dir  $(AT_OUT) \
	  --threads  $(THREADS) \
	  --engine   blast

## mu-clean-arabidopsis: remove all intermediate files for both engine output dirs
mu-clean-arabidopsis:
	rm -f $(AT_OUT_MM2)/tag_hits.sam $(AT_OUT_MM2)/hits.tsv
	rm -f $(AT_OUT_MM2)/tracts.fa $(AT_OUT_MM2)/tracts.bam $(AT_OUT_MM2)/tracts.bam.bai
	rm -f $(AT_OUT_BLAST)/reads.fa $(AT_OUT_BLAST)/blast_hits.tsv
	rm -rf $(AT_OUT_BLAST)/reads_db
	rm -f $(AT_OUT_BLAST)/hits.tsv
	rm -f $(AT_OUT_BLAST)/tracts.fa $(AT_OUT_BLAST)/tracts.bam $(AT_OUT_BLAST)/tracts.bam.bai

.PHONY: mu-arabidopsis mu-arabidopsis-blast mu-benchmark \
        mu-prepare-arabidopsis mu-clean-arabidopsis

# ──────────────────────────────────────────────────
# Arabidopsis genome (TAIR10) — still needed for Phase 1
# ──────────────────────────────────────────────────

SS_GENOME_URL_AT := https://ftp.ensemblgenomes.ebi.ac.uk/pub/plants/release-57/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz
AT_GENOME        := data/genomes/arabidopsis/TAIR10.fa
AT_GENOME_FAI    := $(AT_GENOME).fai

genome-arabidopsis: $(AT_GENOME_FAI)

$(AT_GENOME_FAI): $(AT_GENOME)
	samtools faidx $<

$(AT_GENOME):
	mkdir -p data/genomes/arabidopsis
	curl -k -L $(SS_GENOME_URL_AT) | gunzip > $@
	@echo "Downloaded TAIR10: $$(wc -c < $@) bytes"
	@echo "Chromosomes: $$(grep -c '>' $@)"

# ──────────────────────────────────────────────────
# Annotation tools (keep: EDTA output for arabidopsis still in
# data/semisyn/annotations/arabidopsis/ and may be reused)
# ──────────────────────────────────────────────────

ANNOTATIONS     := data/semisyn/annotations
SS_THREADS      := 16

semisyn-run-edta:
	@[ -n "$(SS_SPECIES)" ] || (echo "Usage: make semisyn-run-edta SS_SPECIES=arabidopsis" && exit 1)
	mkdir -p $(ANNOTATIONS)/$(SS_SPECIES)
	@[ -f $(ANNOTATIONS)/$(SS_SPECIES)/$$(basename $(SS_GENOME)) ] || \
	  cp $(SS_GENOME) $(ANNOTATIONS)/$(SS_SPECIES)/
	docker run --rm \
	  -v $$(realpath $(ANNOTATIONS)/$(SS_SPECIES)):/work -w /work \
	  oushujun/edta:2.0.0 \
	  EDTA.pl \
	    --genome /work/$$(basename $(SS_GENOME)) \
	    --species others \
	    --anno 1 \
	    --threads $(SS_THREADS)

.PHONY: genome-arabidopsis semisyn-run-edta

# ──────────────────────────────────────────────────────────────────────────────
# Phase 3: Multi-species validation
# ──────────────────────────────────────────────────────────────────────────────

## prepare-conifers: extract conifer paralog dirs from zip and concatenate per-family FASTAs
prepare-conifers:
	cd $(COSSU_REF) && unzip -o evx260_supp.zip \
	  "Supporting_Data_S1/PICEA_ABIES/*" \
	  "Supporting_Data_S1/PICEA_GLAUCA/*" \
	  "Supporting_Data_S1/PINUS_TAEDA/*" \
	  "Supporting_Data_S1/PINUS_LAMBERTIANA/*"
	mkdir -p $(COSSU_CON)
	cat $(COSSU_S1)/PICEA_ABIES/*.fa     > $(COSSU_CON)/complete_Picea_abies.fa
	cat $(COSSU_S1)/PICEA_GLAUCA/*.fa    > $(COSSU_CON)/complete_Picea_glauca.fa
	cat $(COSSU_S1)/PINUS_TAEDA/*.fa     > $(COSSU_CON)/complete_Pinus_taeda.fa
	cat $(COSSU_S1)/PINUS_LAMBERTIANA/*.fa > $(COSSU_CON)/complete_Pinus_lambertiana.fa
	@echo "Conifer paralog FASTAs ready:"
	@grep -c '>' $(COSSU_CON)/complete_Picea_abies.fa     | xargs -I{} echo "  Picea abies:      {} sequences"
	@grep -c '>' $(COSSU_CON)/complete_Picea_glauca.fa    | xargs -I{} echo "  Picea glauca:     {} sequences"
	@grep -c '>' $(COSSU_CON)/complete_Pinus_taeda.fa     | xargs -I{} echo "  Pinus taeda:      {} sequences"
	@grep -c '>' $(COSSU_CON)/complete_Pinus_lambertiana.fa | xargs -I{} echo "  Pinus lambertiana:{} sequences"

# ── Per-species download + pipeline template ──────────────────────────────────
# Generates targets: download-$(sp) and mu-$(sp)-mm2 for each species in SPECIES_LIST.
# Reads land at:  data/reads/$(sp)/$(SRA)_1.fastq.gz  (and _2.fastq.gz)
# Results go to:  data/cossu/$(sp)-mm2/results.tsv
#
# Download is idempotent: skips fasterq-dump if _1.fastq.gz already exists.
# Uses fasterq-dump from sra-tools (nixpkgs#sratoolkit).
# ERR/SRR accessions both work with fasterq-dump.

define SPECIES_TEMPLATE
.PHONY: download-$(1) mu-$(1)-mm2

## download-$(1): fetch WGS reads for $(1) ($(SPECIES_$(1)_SRA)) from ENA/SRA
download-$(1):
	mkdir -p data/reads/$(1)
	@if [ -f data/reads/$(1)/$(SPECIES_$(1)_SRA)_1.fastq.gz ]; then \
	  echo "$(1): reads already present, skipping download"; \
	else \
	  fasterq-dump $(SPECIES_$(1)_SRA) \
	    --outdir data/reads/$(1)/ --split-files --threads $(THREADS) \
	    --temp data/reads/$(1)/ && \
	  gzip data/reads/$(1)/$(SPECIES_$(1)_SRA)_1.fastq \
	       data/reads/$(1)/$(SPECIES_$(1)_SRA)_2.fastq; \
	fi

## mu-$(1)-mm2: run M/U pipeline (minimap2) for $(1)
mu-$(1)-mm2:
	mkdir -p data/cossu/$(1)-mm2
	$(PYTHON) -m scripts.pipeline.cli all \
	  --paralogs $(SPECIES_$(1)_PARALOGS) \
	  --reads    data/reads/$(1)/$(SPECIES_$(1)_SRA)_1.fastq.gz \
	             data/reads/$(1)/$(SPECIES_$(1)_SRA)_2.fastq.gz \
	  --out-dir  data/cossu/$(1)-mm2 \
	  --threads  $(THREADS) \
	  --engine   minimap2
endef

$(foreach sp,$(SPECIES_LIST),$(eval $(call SPECIES_TEMPLATE,$(sp))))

# ── Aggregate targets ─────────────────────────────────────────────────────────

## download-all: download reads for all 10 non-Arabidopsis species
download-all: $(addprefix download-,$(filter-out arabidopsis,$(SPECIES_LIST)))

## mu-all: run pipeline for all 11 species (Arabidopsis reads must already exist)
mu-all: $(addprefix mu-,$(addsuffix -mm2,$(SPECIES_LIST)))

## mu-validate: compare all results against Cossu expected ratios
mu-validate:
	$(PYTHON) -m scripts.pipeline.validate \
	  --expected $(COSSU_EXPECTED) \
	  --results-dir data/cossu \
	  --tolerance 0.15

.PHONY: prepare-conifers download-all mu-all mu-validate
